version: '3'
services:
  service-one:
    image: taion809/envoy-examples-fecho
    networks:
      app_net:
        ipv4_address: 172.16.240.10
  service-two:
    image: taion809/envoy-examples-fecho
    networks:
      app_net:
        ipv4_address: 172.16.240.11
  envoy:
    image: taion809/envoy:latest
    ports:
      - "8889:80"
    depends_on:
      - service-one
      - service-two
    networks:
      - app_net
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./srv:/srv
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.240.0/24
