version: 2
jobs:
  "hello-world":
    machine: true
    steps:
      - checkout
      - run: pip install -U docker-compose
      - run:
          command: | 
            cd hello_world
            docker-compose up -d
            curl -I localhost:8889
            docker-compose down

  "access-logs":
    machine: true
    steps:
      - checkout
      - run: pip install -U docker-compose
      - run: 
          command: |
            cd access_logs
            docker-compose up -d
            curl -I localhost:8889
            docker-compose down

      - run:
          command: | 
            if [[ ! -f access_logs/logs/ingress_http_200.log ]]; then
              echo "Access log wasn't found"
              ls -l access_logs/logs
              exit 1
            fi

workflows:
  version: 2
  all:
    jobs:
      - "hello-world"
      - "access-logs"
