version: 2
jobs:
  "hello-world":
    machine: true
    steps:
      - checkout
      - run: pip install -U docker-compose

  "access-logs":
    machine: true
    steps:
      - checkout
      - run: pip install -U docker-compose

workflows:
  version: 2
  all:
    jobs:
      - "hello-world"
      - "access-logs"
